SELECT 
    A.AUTHOR_ID,
    A.AUTHOR_NAME,
    B.CATEGORY,
    SUM(B.PRICE * S.SALES) AS TOTAL_SALES
FROM 
    BOOK B
INNER JOIN 
    AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
INNER JOIN 
    BOOK_SALES S ON B.BOOK_ID = S.BOOK_ID
WHERE 
    S.SALES_DATE BETWEEN TO_DATE('2022-01-01', 'YYYY-MM-DD') 
                     AND TO_DATE('2022-01-31', 'YYYY-MM-DD')
GROUP BY 
    A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY
ORDER BY 
    A.AUTHOR_ID, B.CATEGORY DESC;