-- 코드를 입력하세요
SELECT APNT_NO,PT_NAME,A.PT_NO,A.MCDP_CD,DR_NAME,APNT_YMD
FROM PATIENT P,DOCTOR D,APPOINTMENT A
WHERE P.PT_NO = A.PT_NO
AND D.DR_ID = A.MDDR_ID
AND APNT_YMD LIKE "2022-04-13%"
AND APNT_CNCL_YMD IS NULL
AND A.MCDP_CD = "CS"
ORDER BY APNT_YMD;