-- 코드를 입력하세요
SELECT USER_ID, NICKNAME, SUM(PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD B, USED_GOODS_USER U
WHERE B.WRITER_ID = U.USER_ID
AND STATUS = 'DONE'
GROUP BY WRITER_ID
HAVING SUM(PRICE)>=700000
ORDER BY SUM(PRICE);

